
package ec.edu.espe.Billing.view;
import javax.swing.JOptionPane;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import java.util.ArrayList;
/**
 *
 * @author Christopher Lomas,<CodeBros,@ESPE>
 */
public class FrmSale extends javax.swing.JFrame {
    private ArrayList<String> customerIds = new ArrayList<>();
    private ArrayList<String> productIds = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSale.class.getName());

    /**
     * Creates new form FrmSale
     */
    public FrmSale() {
    initComponents();
        this.setLocationRelativeTo(null);
        
        
        loadCustomersFromMongoDB();
        
        
        cmbCategoryFilter.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadProductsByCategory();
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegisterSale = new javax.swing.JButton();
        txtInvoiceNumber = new javax.swing.JTextField();
        cmbProduct = new javax.swing.JComboBox<>();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbCashier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbCategoryFilter = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtCashReceived = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REALIZAR VENTA");

        jLabel2.setText("Nro Factura:");

        jLabel3.setText("Cajero:");

        jLabel4.setText("Seleccionar Cliente: ");

        jLabel5.setText("Seleccionar Producto:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Método de Pago:");

        btnRegisterSale.setText("Registrar Venta");
        btnRegisterSale.addActionListener(this::btnRegisterSaleActionPerformed);

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", "Tarjeta" }));
        cmbPaymentMethod.addActionListener(this::cmbPaymentMethodActionPerformed);

        btnBack.setText("Regresar al Menu Principal");
        btnBack.addActionListener(this::btnBackActionPerformed);

        cmbCashier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santiago Lomas", "Mateo Lomas", " ", " " }));

        jLabel8.setText("Categoría: ");

        cmbCategoryFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría...", "Snacks", "Bebidas normales o jugos", "Gaseosas", "Bebidas alcoholicas", "Dulces", "Galletas", "Productos de aseo personal" }));

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("Efectivo Recibido:");

        txtCashReceived.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnRegisterSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(txtCashReceived))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCashReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterSale)
                    .addComponent(btnBack))
                .addGap(155, 155, 155))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSaleActionPerformed
    
        String invoiceNum = txtInvoiceNumber.getText().trim();
        String cashier = cmbCashier.getSelectedItem().toString();
        
        int customerIndex = cmbCustomer.getSelectedIndex();
        int productIndex = cmbProduct.getSelectedIndex();
        int quantity = (Integer) spnQuantity.getValue();
        String paymentMethod = cmbPaymentMethod.getSelectedItem().toString();
        
   
        if (invoiceNum.isEmpty() || customerIndex <= 0 || productIndex <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, complete el número de factura, seleccione un cliente y un producto antes de procesar.", 
                "Datos Incompletos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String customerRuc = customerIds.get(customerIndex);
        String productId = productIds.get(productIndex);
        
        try {
            com.mongodb.client.MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
            com.mongodb.client.MongoCollection<org.bson.Document> productCollection = database.getCollection("Product");
            com.mongodb.client.MongoCollection<org.bson.Document> saleCollection = database.getCollection("Sales");
            
            
            org.bson.Document productDoc = productCollection.find(com.mongodb.client.model.Filters.eq("productId", productId)).first();
            if (productDoc == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "El producto seleccionado ya no existe en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int currentStock = productDoc.getInteger("stock");
            String productName = productDoc.getString("name");
            double price = productDoc.getDouble("price");
            
            
            if (quantity > currentStock) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "No se puede realizar la venta.\nEl producto " + productName + " solo cuenta con " + currentStock + " unidades en stock.", 
                    "Stock Insuficiente", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
            double totalSales = price * quantity;
            double cashReceived = 0.0;

           
            if (paymentMethod.equalsIgnoreCase("Efectivo")) {
                try {
                    String cashText = txtCashReceived.getText().trim();
                    if (!cashText.isEmpty()) {
                        cashReceived = Double.parseDouble(cashText);
                        
                        
                        if (cashReceived < totalSales) {
                            javax.swing.JOptionPane.showMessageDialog(this, 
                                "El efectivo recibido ($" + cashReceived + ") es menor al total a pagar ($" + totalSales + ").", 
                                "Efectivo Insuficiente", 
                                javax.swing.JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    } else {
                        cashReceived = totalSales; // Si el cajero lo dejó vacío, asumimos pago exacto
                    }
                } catch (NumberFormatException nfe) {
                    cashReceived = totalSales; 
                }
            } else {
            
                cashReceived = totalSales;
            }
            
            
            int newStock = currentStock - quantity;
            productCollection.updateOne(com.mongodb.client.model.Filters.eq("productId", productId), 
                                        com.mongodb.client.model.Updates.set("stock", newStock));
            
            
            org.bson.Document saleDoc = new org.bson.Document("invoiceNumber", invoiceNum)
                    .append("cashier", cashier)
                    .append("customerRuc", customerRuc)
                    .append("productId", productId)
                    .append("productName", productName)
                    .append("quantity", quantity)
                    .append("total", totalSales)
                    .append("paymentMethod", paymentMethod)
                    .append("cashReceived", cashReceived) 
                    .append("timestamp", new java.util.Date()); // Clave para jalar la ÚLTIMA factura
                    
            saleCollection.insertOne(saleDoc);
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "¡Venta Registrada con Éxito!\nEl stock global ha sido descontado correctamente.", 
                "Facturación Exitosa", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            
            loadProductsByCategory();
            
            
            txtInvoiceNumber.setText("");
            if (txtCashReceived.isEnabled()) {
                txtCashReceived.setText("");
            } else {
                txtCashReceived.setText("0.0");
            }
            spnQuantity.setValue(1);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error crítico al procesar la venta en la base de datos: " + e.getMessage(), 
                "Error de Transacción", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterSaleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentMethodActionPerformed
    
    String selectedMethod = cmbPaymentMethod.getSelectedItem().toString();
    
    
    if (selectedMethod.equalsIgnoreCase("Efectivo")) {
        txtCashReceived.setEnabled(true);
        txtCashReceived.setText(""); 
    } else {
    
        txtCashReceived.setEnabled(false);
        txtCashReceived.setText("0.0");
    }
    }//GEN-LAST:event_cmbPaymentMethodActionPerformed
private void loadCustomersFromMongoDB() {
        cmbCustomer.removeAllItems();
        customerIds.clear();
        
        cmbCustomer.addItem("Seleccione un cliente...");
        customerIds.add(""); 
        
        try {
            MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Customer");
            
            for (Document doc : collection.find()) {
                String ruc = doc.getString("ruc");
                String name = doc.getString("name");
                
                cmbCustomer.addItem(name + " (RUC: " + ruc + ")");
                customerIds.add(ruc); 
            }
        } catch (Exception e) {
            System.out.println("Error al cargar clientes: " + e.getMessage());
        }
    }

private void loadProductsByCategory() {
        cmbProduct.removeAllItems();
        productIds.clear();
        
        cmbProduct.addItem("Seleccione un producto...");
        productIds.add(""); 
        
        if (cmbCategoryFilter.getSelectedIndex() == 0) {
            return;
        }
        
        String selectedCategory = cmbCategoryFilter.getSelectedItem().toString();
        
        try {
            MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Product");
            
            
            for (Document doc : collection.find(Filters.eq("category", selectedCategory))) {
                String id = doc.getString("productId");
                String name = doc.getString("name");
                int stock = doc.getInteger("stock");
                
                
                cmbProduct.addItem(name + " (" + stock + " u. disponibles)");
                productIds.add(id); 
            }
        } catch (Exception e) {
            System.out.println("Error al cargar productos filrados: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new FrmSale().setVisible(true);
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterSale;
    private javax.swing.JComboBox<String> cmbCashier;
    private javax.swing.JComboBox<String> cmbCategoryFilter;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtCashReceived;
    private javax.swing.JTextField txtInvoiceNumber;
    // End of variables declaration//GEN-END:variables
}
