
package ec.edu.espe.Billing.view;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Sorts;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.Date;
import org.bson.conversions.Bson;
/**
 *
 * @author Christopher Lomas,<CodeBros,@ESPE>
 */
public class FrmReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReport.class.getName());

    /**
     * Creates new form FrmReport
     */
    public FrmReport() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadReportData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbPeriodFilter = new javax.swing.JComboBox<>();
        lblGrandTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REPORTE DE VENTAS ");

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro Factura", "Cajero", "Cliente", "Método de Pago", "Total de Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        btnBack.setText("Volver al Menú Principal");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel2.setText("Filtrar Período: ");

        cmbPeriodFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los registros", "Esta Semana", "Este Mes" }));
        cmbPeriodFilter.addActionListener(this::cmbPeriodFilterActionPerformed);

        lblGrandTotal.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(0, 204, 51));
        lblGrandTotal.setText("Total Ganado: $0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPeriodFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbPeriodFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblGrandTotal)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void loadReportData() {
        
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        model.setRowCount(0); 
        
        String selectedPeriod = cmbPeriodFilter.getSelectedItem().toString();
        Bson filter = Filters.empty(); 
        
        Calendar cal = Calendar.getInstance();
        Date now = cal.getTime();
        
        
        if (selectedPeriod.equalsIgnoreCase("Esta Semana")) {
            cal.add(Calendar.DAY_OF_YEAR, -7);
            Date oneWeekAgo = cal.getTime();
            
            filter = Filters.and(Filters.gte("timestamp", oneWeekAgo), Filters.lte("timestamp", now));
            
        } else if (selectedPeriod.equalsIgnoreCase("Este Mes")) {
            cal.add(Calendar.DAY_OF_YEAR, -30);
            Date oneMonthAgo = cal.getTime();
            
            filter = Filters.and(Filters.gte("timestamp", oneMonthAgo), Filters.lte("timestamp", now));
        }
        
        double grandTotal = 0.0;
        
        try {
            MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
            MongoCollection<Document> saleCollection = database.getCollection("Sales");
            MongoCollection<Document> customerCollection = database.getCollection("Customer");
            
            
            for (Document saleDoc : saleCollection.find(filter).sort(Sorts.descending("timestamp"))) {
                String invoiceNum = saleDoc.getString("invoiceNumber");
                String cashier = saleDoc.getString("cashier");
                String customerRuc = saleDoc.getString("customerRuc");
                String paymentMethod = saleDoc.getString("paymentMethod");
                double totalSale = saleDoc.getDouble("total");
                
            
                grandTotal += totalSale;
                
            
                Document custDoc = customerCollection.find(Filters.eq("ruc", customerRuc)).first();
                String customerName = (custDoc != null) ? custDoc.getString("name") : "Consumidor Final";
                
            
                model.addRow(new Object[]{
                    invoiceNum,
                    cashier,
                    customerName,
                    paymentMethod,
                    String.format("$%.2f", totalSale)
                });
            }
            
            
            lblGrandTotal.setText(String.format("Total Ganado: $%.2f", grandTotal));
            
           
            MongoCollection<Document> reportCollection = database.getCollection("Reports");
                
                Document logDoc = new Document("reportType", "Consulta de Ventas")
                    .append("periodFilter", selectedPeriod)
                    .append("totalReported", grandTotal)
                    .append("timestamp", new java.util.Date())
                    .append("generatedBy", "UsuarioActual"); 
                
                reportCollection.insertOne(logDoc);
                System.out.println("Auditoría de reporte guardada en MongoDB.");
            

            
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar el reporte: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }  
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbPeriodFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPeriodFilterActionPerformed
    loadReportData();
    }//GEN-LAST:event_cmbPeriodFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbPeriodFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
