
package ec.edu.espe.Billing.view;
import ec.edu.espe.Billing.controller.InvoiceController;
import ec.edu.espe.Billing.model.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
/**
 *
 * @author Christopher Lomas,<CodeBros,@ESPE>
 */
public class BillingVista extends javax.swing.JFrame {
    private Company company;
    private Customer customer;
    private Product product;
    private Payment payment;
    private Invoice invoice;
    private ArrayList<Product> inventory;
    private ArrayList<Customer> customers;

    private JPanel mainPanel;
    private CardLayout cardLayout;
    private JMenuBar menuBar;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillingVista.class.getName());

    /**
     * Creates new form BillingVista
     */
    public BillingVista() {
        initComponents();
        
    this.company = new Company();
    this.customer = new Customer();
    this.product = new Product();
    this.payment = new Payment();
    this.inventory = InvoiceController.loadInventory();
    this.customers = InvoiceController.loadCustomers();

    setTitle("Sistema de Facturación - Micromercado La Victoria");
    setSize(900, 700);
    setLocationRelativeTo(null);

    cardLayout = new CardLayout();
    mainPanel = new JPanel(cardLayout);
    mainPanel.setBackground(new Color(245, 245, 245));

    initLoginScreen();
    initMainMenu();

        this.setContentPane(mainPanel);
        this.revalidate();
        this.repaint();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void initLoginScreen() {
        JPanel loginPanel = new JPanel(new GridBagLayout());
        loginPanel.setBackground(new Color(230, 240, 250));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(15, 15, 15, 15);

        JLabel titleLabel = new JLabel("INICIO DE SESIÓN - DUEÑO");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 20));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        loginPanel.add(titleLabel, gbc);

        gbc.gridwidth = 1;
        gbc.gridy = 1; gbc.gridx = 0;
        loginPanel.add(new JLabel("Usuario:"), gbc);
        JTextField userField = createStyledTextField();
        gbc.gridx = 1;
        loginPanel.add(userField, gbc);

        gbc.gridy = 2; gbc.gridx = 0;
        loginPanel.add(new JLabel("Contraseña:"), gbc);
        JPasswordField passField = new JPasswordField(15);
        passField.setFont(new Font("Arial", Font.PLAIN, 14));
        gbc.gridx = 1;
        loginPanel.add(passField, gbc);

        JButton loginBtn = new JButton("Ingresar");
        loginBtn.setBackground(new Color(0, 102, 204));
        loginBtn.setForeground(Color.WHITE);
        gbc.gridy = 3; gbc.gridx = 0; gbc.gridwidth = 2;
        loginPanel.add(loginBtn, gbc);

        ActionListener loginAction = e -> {
            String username = userField.getText();
            String password = new String(passField.getPassword());

            if (username.equals("MayraJHF") && password.equals("171206")) {
                menuBar = createMenuBar();
                setJMenuBar(menuBar);
                cardLayout.show(mainPanel, "MainMenu");
                revalidate();
            } else {
                showError("Usuario o contraseña incorrectos.");
            }
        };

        loginBtn.addActionListener(loginAction);
        passField.addActionListener(loginAction);

        mainPanel.add(loginPanel, "Login");
    }

    private void initMainMenu() {
        JPanel menuPanel = new JPanel(new BorderLayout());
        menuPanel.setBackground(Color.WHITE);
        
        JLabel welcomeLabel = new JLabel("<html><center>BIENVENIDO AL SISTEMA<br>Micromercado La Victoria</center></html>", SwingConstants.CENTER);
        welcomeLabel.setFont(new Font("Serif", Font.BOLD, 32));
        welcomeLabel.setForeground(new Color(0, 51, 102));
        menuPanel.add(welcomeLabel, BorderLayout.CENTER);
        
        JLabel footer = new JLabel("Pase el mouse por el menú superior para ver las opciones", SwingConstants.CENTER);
        footer.setBorder(new EmptyBorder(20, 20, 20, 20));
        menuPanel.add(footer, BorderLayout.SOUTH);

        mainPanel.add(menuPanel, "MainMenu");
    }

    private JMenuBar createMenuBar() {
JMenuBar bar = new JMenuBar() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;
            
            g2d.setColor(new Color(240, 240, 240)); 
            g2d.fillRect(0, 0, getWidth(), getHeight());
        }
    };

    
    Color fontColor = new Color(0, 51, 102); 

    JMenu companyMenu = createHoverMenu("EMPRESA", new String[]{"Registrar Empresa"}, e -> showCompanyForm());
    companyMenu.setForeground(fontColor);
    
    JMenu customerMenu = createHoverMenu("CLIENTE", new String[]{"Registrar Cliente", "Eliminar Cliente"}, e -> {
        if (e.getActionCommand().equals("Registrar Cliente")) showCustomerForm();
        else deleteCustomer();
    });
    customerMenu.setForeground(fontColor);
    
    JMenu productMenu = createHoverMenu("PRODUCTO", new String[]{"Registrar Producto", "Ver Inventario", "Eliminar Producto"}, e -> {
        String cmd = e.getActionCommand();
        if (cmd.equals("Registrar Producto")) showProductForm();
        else if (cmd.equals("Ver Inventario")) showInventory();
        else deleteProduct();
    });
    productMenu.setForeground(fontColor);
    
    JMenu salesMenu = createHoverMenu("VENTAS", new String[]{"Realizar Venta", "Imprimir Factura"}, e -> {
        if (e.getActionCommand().equals("Realizar Venta")) showSaleForm();
        else printInvoice();
    });
    salesMenu.setForeground(fontColor);
    
    JMenu exitMenu = new JMenu("SALIR");
    exitMenu.setForeground(fontColor);
    exitMenu.setFont(new Font("Arial", Font.BOLD, 12));
    exitMenu.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            int confirm = JOptionPane.showConfirmDialog(null, "¿Desea salir del sistema?", "Confirmar Salida", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) System.exit(0);
        }
    });

    bar.add(companyMenu);
    bar.add(customerMenu);
    bar.add(productMenu);
    bar.add(salesMenu);
    bar.add(exitMenu);

    return bar;
    }

    private JMenu createHoverMenu(String title, String[] items, ActionListener action) {
        JMenu menu = new JMenu(title);
        menu.setForeground(Color.WHITE);
        menu.setFont(new Font("Arial", Font.BOLD, 12));
        
        for (String item : items) {
            JMenuItem menuItem = new JMenuItem(item);
            menuItem.addActionListener(action);
            menu.add(menuItem);
        }
        
        return menu;
    }

    private void showCompanyForm() {
        JPanel panel = createFormPanel("REGISTRO DE EMPRESA");
        JTextField idField = addField(panel, "RUC (10 dígitos):");
        JTextField nameField = addField(panel, "Nombre:");
        JTextField addrField = addField(panel, "Dirección:");

        JButton regBtn = new JButton("Registrar");
        panel.add(regBtn, createGbc(0, panel.getComponentCount(), 2));

        regBtn.addActionListener(e -> {
            if (validateInput(idField.getText(), "\\d{10}", "El RUC debe tener 10 números.") &&
                validateInput(nameField.getText(), "[a-zA-Z\\s]+", "El nombre solo debe contener letras.")) {
                company.setCompanyId(idField.getText());
                company.setCompanyName(nameField.getText());
                company.setCompanyAddress(addrField.getText());
                showSuccess("Empresa registrada.");
                cardLayout.show(mainPanel, "MainMenu");
            }
        });

        showPanel(panel, "CompanyForm");
    }

    private void showCustomerForm() {
        JPanel panel = createFormPanel("REGISTRO DE CLIENTE");
        JTextField rucField = addField(panel, "RUC (10 dígitos):");
        JTextField nameField = addField(panel, "Nombre:");
        JTextField addrField = addField(panel, "Dirección:");
        JTextField mailField = addField(panel, "Email:");

        JButton regBtn = new JButton("Registrar");
        panel.add(regBtn, createGbc(0, panel.getComponentCount(), 2));

        regBtn.addActionListener(e -> {
            if (validateInput(rucField.getText(), "\\d{10}", "El RUC debe tener 10 números.") &&
                validateInput(nameField.getText(), "[a-zA-Z\\s]+", "El nombre solo debe contener letras.")) {
                Customer c = new Customer(rucField.getText(), nameField.getText(), addrField.getText(), mailField.getText());
                customers.add(c);
                InvoiceController.saveCustomers(customers);
                customer = c;
                showSuccess("Cliente registrado y guardado.");
                cardLayout.show(mainPanel, "MainMenu");
            }
        });

        showPanel(panel, "CustomerForm");
    }

    private void showProductForm() {
        JPanel panel = createFormPanel("REGISTRO DE PRODUCTO");
        JTextField idField = addField(panel, "ID (Números):");
        JTextField nameField = addField(panel, "Nombre:");
        JTextField priceField = addField(panel, "Precio (Ej: 10.50):");
        JTextField stockField = addField(panel, "Stock (Números):");

        JButton regBtn = new JButton("Registrar");
        panel.add(regBtn, createGbc(0, panel.getComponentCount(), 2));

        regBtn.addActionListener(e -> {
            if (validateInput(idField.getText(), "\\d+", "ID inválido.") &&
                validateInput(nameField.getText(), "[a-zA-Z\\s]+", "Nombre inválido.") &&
                validateInput(priceField.getText(), "\\d+(\\.\\d+)?", "Precio inválido.") &&
                validateInput(stockField.getText(), "\\d+", "Stock inválido.")) {
                
                Product p = new Product();
                p.setId(idField.getText());
                p.setName(nameField.getText());
                p.setUnitPrice(Double.parseDouble(priceField.getText()));
                p.setStock(Integer.parseInt(stockField.getText()));
                inventory.add(p);
                InvoiceController.saveInventory(inventory);
                showSuccess("Producto registrado y guardado.");
                cardLayout.show(mainPanel, "MainMenu");
            }
        });

        showPanel(panel, "ProductForm");
    }

    private void showSaleForm() {
        if (inventory.isEmpty()) {
            showError("No hay productos en el inventario.");
            return;
        }
        if (customers.isEmpty()) {
            showError("Primero registre un cliente.");
            return;
        }

        JPanel panel = createFormPanel("REALIZAR VENTA");
        JTextField invField = addField(panel, "Nro Factura:");
        JTextField cashField = addField(panel, "Cajero:");
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        
        gbc.gridx = 0; gbc.gridy = panel.getComponentCount();
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(new JLabel("Seleccionar Cliente:"), gbc);
        
        JComboBox<Customer> custCombo = new JComboBox<>(customers.toArray(new Customer[0]));
        custCombo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Customer c) setText(c.getName() + " (" + c.getRuc() + ")");
                return this;
            }
        });
        gbc.gridx = 1; gbc.anchor = GridBagConstraints.WEST;
        panel.add(custCombo, gbc);

        gbc.gridx = 0; gbc.gridy = panel.getComponentCount();
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(new JLabel("Seleccionar Producto:"), gbc);
        
        JComboBox<Product> prodCombo = new JComboBox<>(inventory.toArray(new Product[0]));
        prodCombo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Product p) setText(p.getName() + " (Stock: " + p.getStock() + ")");
                return this;
            }
        });
        gbc.gridx = 1; gbc.anchor = GridBagConstraints.WEST;
        panel.add(prodCombo, gbc);

        JTextField qtyField = addField(panel, "Cantidad:");
        
        gbc.gridx = 0; gbc.gridy = panel.getComponentCount();
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(new JLabel("Método de Pago:"), gbc);
        
        String[] methods = {"Efectivo", "Transferencia", "Tarjeta"};
        JComboBox<String> payCombo = new JComboBox<>(methods);
        gbc.gridx = 1; gbc.anchor = GridBagConstraints.WEST;
        panel.add(payCombo, gbc);

        JButton saleBtn = new JButton("Registrar Venta");
        panel.add(saleBtn, createGbc(0, panel.getComponentCount(), 2));

        saleBtn.addActionListener(e -> {
            if (validateInput(invField.getText(), "\\d+", "Nro Factura inválido.") &&
                validateInput(cashField.getText(), "[a-zA-Z\\s]+", "Nombre de cajero inválido.") &&
                validateInput(qtyField.getText(), "\\d+", "Cantidad inválida.")) {
                
                Customer selectedCust = (Customer) custCombo.getSelectedItem();
                Product selectedProd = (Product) prodCombo.getSelectedItem();
                int qty = Integer.parseInt(qtyField.getText());
                
                if (selectedProd.reduceStock(qty)) {
                    customer = selectedCust;
                    product = selectedProd;
                    invoice = new Invoice(Integer.parseInt(invField.getText()), cashField.getText(), customer.getName());
                    invoice.calculateTotals(selectedProd, qty);
                    
                    payment.setPaymentMethod((String) payCombo.getSelectedItem());
                    payment.setMoneyPurchased(invoice.getTotal());
                    
                    InvoiceController.saveInventory(inventory);
                    showSuccess("Venta procesada. Total: $" + String.format("%.2f", invoice.getTotal()));
                    cardLayout.show(mainPanel, "MainMenu");
                } else {
                    showError("Stock insuficiente para " + selectedProd.getName());
                }
            }
        });

        showPanel(panel, "SaleForm");
    }

    private void deleteProduct() {
        if (inventory.isEmpty()) {
            showError("No hay productos para eliminar.");
            return;
        }
        Product selected = (Product) JOptionPane.showInputDialog(null, "Seleccione producto a eliminar:", "Eliminar Producto",
                JOptionPane.QUESTION_MESSAGE, null, inventory.toArray(), inventory.get(0));
        
        if (selected != null) {
            inventory.remove(selected);
            InvoiceController.saveInventory(inventory);
            showSuccess("Producto eliminado.");
        }
    }

    private void deleteCustomer() {
        if (customers.isEmpty()) {
            showError("No hay clientes registrados.");
            return;
        }
        Customer selected = (Customer) JOptionPane.showInputDialog(null, "Seleccione cliente a eliminar:", "Eliminar Cliente",
                JOptionPane.QUESTION_MESSAGE, null, customers.toArray(), customers.get(0));
        
        if (selected != null) {
            customers.remove(selected);
            InvoiceController.saveCustomers(customers);
            showSuccess("Cliente eliminado.");
        }
    }

    private void printInvoice() {
        if (invoice == null) {
            showError("No hay ventas para imprimir.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        String center = "                                ";
        
        sb.append(center).append("Micromercado La Victoria\n");
        sb.append(center).append(company.getCompanyName()).append("\n");
        sb.append(center).append("RUC: ").append(company.getCompanyId()).append("\n");
        sb.append(center).append("Factura Nro: ").append(invoice.getInvoiceNumber()).append("\n");
        sb.append("\n");
        sb.append("Dirección: Sangolquí\n");
        sb.append("Atendido por: ").append(invoice.getCashier()).append("\n");
        sb.append("Método de Pago: ").append(payment.getPaymentMethod()).append("\n");
        sb.append("\n");
        sb.append("----------------------------------------------------------\n");
        sb.append("CLIENTE: ").append(customer.getName()).append("\n");
        sb.append("RUC: ").append(customer.getRuc()).append("\n");
        sb.append("DIRECCIÓN: ").append(customer.getAddress()).append("\n");
        sb.append("----------------------------------------------------------\n");
        sb.append(String.format("%-20s %-10s %-10s\n", "Producto", "Cant.", "Total"));
        int qty = (int)(invoice.getSubtotal()/product.getUnitPrice());
        sb.append(String.format("%-20s %-10d $%-10.2f\n", product.getName(), qty, invoice.getTotal()));
        sb.append("----------------------------------------------------------\n");
        sb.append("SUBTOTAL: $").append(String.format("%.2f", invoice.getSubtotal())).append("\n");
        sb.append("IVA (15%): $").append(String.format("%.2f", invoice.getSubtotal() * 0.15)).append("\n");
        sb.append("TOTAL:    $").append(String.format("%.2f", invoice.getTotal())).append("\n");
        sb.append("==========================================================\n");

        JTextArea area = new JTextArea(sb.toString());
        area.setFont(new Font("Monospaced", Font.PLAIN, 12));
        area.setEditable(false);
        
        JPanel printPanel = new JPanel(new BorderLayout());
        printPanel.add(new JScrollPane(area), BorderLayout.CENTER);
        JLabel backLabel = new JLabel("Presione ENTER para volver al menú", SwingConstants.CENTER);
        printPanel.add(backLabel, BorderLayout.SOUTH);
        
        area.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) cardLayout.show(mainPanel, "MainMenu");
            }
        });

        showPanel(printPanel, "InvoicePrint");
        area.requestFocusInWindow();
    }

    private void showInventory() {
        StringBuilder sb = new StringBuilder("INVENTARIO ACTUAL\n\n");
        for (Product p : inventory) {
            sb.append("ID: ").append(p.getId()).append(" | ").append(p.getName())
              .append(" | Precio: $").append(p.getUnitPrice()).append(" | Stock: ").append(p.getStock()).append("\n");
        }
        JTextArea area = new JTextArea(sb.toString());
        area.setEditable(false);
        area.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) cardLayout.show(mainPanel, "MainMenu");
            }
        });
        showPanel(new JScrollPane(area), "Inventory");
        area.requestFocusInWindow();
    }

    private JPanel createFormPanel(String title) {
        JPanel p = new JPanel(new GridBagLayout());
        p.setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        JLabel l = new JLabel(title);
        l.setFont(new Font("Arial", Font.BOLD, 18));
        p.add(l, gbc);
        return p;
    }

    private JTextField addField(JPanel p, String label) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.EAST;
        gbc.gridx = 0; gbc.gridy = p.getComponentCount();
        p.add(new JLabel(label), gbc);
        
        JTextField f = createStyledTextField();
        gbc.gridx = 1;
        gbc.anchor = GridBagConstraints.WEST;
        p.add(f, gbc);
        return f;
    }

    private GridBagConstraints createGbc(int x, int y, int width) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(15, 5, 5, 5);
        gbc.gridx = x; gbc.gridy = y;
        gbc.gridwidth = width;
        return gbc;
    }

    private JTextField createStyledTextField() {
        JTextField f = new JTextField(20);
        f.setFont(new Font("Arial", Font.PLAIN, 14));
        return f;
    }

    private void showPanel(Component c, String name) {
        mainPanel.add(c, name);
        cardLayout.show(mainPanel, name);
    }

    private boolean validateInput(String text, String regex, String error) {
        if (text.matches(regex)) return true;
        showError(error);
        return false;
    }

    private void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void showSuccess(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
