package ec.edu.espe.Billing.view;

import com.mongodb.client.MongoDatabase;
import ec.edu.espe.Billing.utils.MongoDBConnection;
import javax.swing.JOptionPane;
import java.awt.Color;


/**
 *
 * @author Christopher Lomas,<CodeBros,@ESPE>
 */
public class FrmLogin extends javax.swing.JFrame {
      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());
      private MongoDatabase database;
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null); 
        connectDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SUPERMERCADO LA VICTORIA ");

        jLabel2.setText("Usuario:");

        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        jLabel3.setText("Contraseña:");

        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblStatus.setText("Conectando a la Base de Datos...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(276, 276, 276))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(54, 54, 54))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectDatabase() {
        try {
            database = MongoDBConnection.getDatabase();
            if (database != null) {
                lblStatus.setText("Conectado a MongoDB Atlas de forma exitosa.");
                lblStatus.setForeground(new Color(0, 153, 51)); // Verde Éxito
            } else {
                lblStatus.setText("Error de conexión: la base de datos devolvió null.");
                lblStatus.setForeground(Color.RED);
            }
        } catch (Exception e) {
            lblStatus.setText("Error al conectar con la Base de Datos.");
            lblStatus.setForeground(Color.RED);
            JOptionPane.showMessageDialog(this, 
                "No se pudo establecer la conexión con la base de datos:\n" + e.getMessage(), 
                "Error de Base de Datos", 
                JOptionPane.ERROR_MESSAGE);
        }
    }



    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, llene todos los campos requeridos.", 
                "Datos Faltantes", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }


        if (username.equals("MayraJHF") && password.equals("171206")) {
            JOptionPane.showMessageDialog(this, 
                "¡Acceso concedido! Bienvenido al Supermercado La Victoria.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose(); 
            
           
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    FrmMenu mainMenu = new FrmMenu("admin");
                    mainMenu.setVisible(true);
                    mainMenu.setLocationRelativeTo(null); // Centra la ventana
                }
            });
        } 
        
        
        else if (username.equals("santiagolomas") && password.equals("santiago123")) {
            JOptionPane.showMessageDialog(this, 
                "¡Acceso concedido!\nBienvenido al sistema, Cajero Santiago Lomas.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    FrmMenu mainMenu = new FrmMenu("cashier");
                    mainMenu.setVisible(true);
                    mainMenu.setLocationRelativeTo(null);
                }
            });
        } 
        
        
        else if (username.equals("mateolomas") && password.equals("mateo123")) {
            JOptionPane.showMessageDialog(this, 
                "¡Acceso concedido!\nBienvenido al sistema, Cajero Mateo Lomas.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    FrmMenu mainMenu = new FrmMenu("cashier");
                    mainMenu.setVisible(true);
                    mainMenu.setLocationRelativeTo(null);
                }
            });
        } 
        
      
        else {
            JOptionPane.showMessageDialog(this, 
                "Usuario o contraseña incorrectos. Acceso denegado.", 
                "Fallo de Autenticación", 
                JOptionPane.ERROR_MESSAGE);
            txtPassword.setText("");
            txtUsername.requestFocus();
        }
        
        try {
        com.mongodb.client.MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
        com.mongodb.client.MongoCollection<org.bson.Document> usersCollection = database.getCollection("Users");
        
       
        org.bson.Document userQuery = usersCollection.find(com.mongodb.client.model.Filters.eq("username", username)).first();
        
        if (userQuery != null) {
            String passwordBD = userQuery.getString("password");
            String role = userQuery.getString("role");
            
       
            if (password.equals(passwordBD)) {
                JOptionPane.showMessageDialog(this, 
                    "¡Acceso concedido! Rol: " + role.toUpperCase(), 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
                
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        FrmMenu mainMenu = new FrmMenu(role); // Le pasa el rol dinámico "admin" o "cashier"
                        mainMenu.setVisible(true);
                        mainMenu.setLocationRelativeTo(null);
                    }
                });
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Fallo de Autenticación", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El usuario no existe en la base de datos.", "Fallo de Autenticación", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error de conexión al validar usuario: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
