
package ec.edu.espe.Billing.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Sorts;
import com.mongodb.client.model.Updates;
import java.util.ArrayList;
/**
 *
 * @author Christopher Lomas,<CodeBros,@ESPE>
 */
public class FrmSale extends javax.swing.JFrame {
    private ArrayList<String> customerIds = new ArrayList<>();
    private ArrayList<String> productIds = new ArrayList<>();
    private DefaultTableModel tableModel;
    private boolean isAddingProduct = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSale.class.getName());

    /**
     * Creates new form FrmSale
     */
    public FrmSale() {
        initComponents();
        this.setLocationRelativeTo(null);
        calculateTotal();
        for (java.awt.event.ActionListener al : btnAddProduct.getActionListeners()) {
        btnAddProduct.removeActionListener(al);
    }
        
        generateNextInvoiceNumber();
        
        tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0); 

        
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddProductActionPerformed(evt);
        }
            });
        
        loadCategoriesFromMongoDB();
        loadCustomersFromMongoDB();
        generateNextInvoiceNumber();
        
        cmbCategoryFilter.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadProductsByCategory();
            }
        });
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegisterSale = new javax.swing.JButton();
        txtInvoiceNumber = new javax.swing.JTextField();
        cmbProduct = new javax.swing.JComboBox<>();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbCashier = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbCategoryFilter = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtCashReceived = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblTotalAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REALIZAR VENTA");

        jLabel2.setText("Nro Factura:");

        jLabel3.setText("Cajero:");

        jLabel4.setText("Seleccionar Cliente: ");

        jLabel5.setText("Seleccionar Producto:");

        jLabel6.setText("Cantidad:");

        jLabel7.setText("Método de Pago:");

        btnRegisterSale.setText("Registrar Venta");
        btnRegisterSale.addActionListener(this::btnRegisterSaleActionPerformed);

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", "Tarjeta" }));
        cmbPaymentMethod.addActionListener(this::cmbPaymentMethodActionPerformed);

        btnBack.setText("Regresar al Menu Principal");
        btnBack.addActionListener(this::btnBackActionPerformed);

        cmbCashier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Santiago Lomas", "Mateo Lomas", " ", " " }));

        jLabel8.setText("Categoría: ");

        cmbCategoryFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoría...", "Snacks", "Bebidas normales o jugos", "Gaseosas", "Bebidas alcoholicas", "Dulces", "Galletas", "Productos de aseo personal" }));

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("Efectivo Recibido:");

        txtCashReceived.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Producto", "Precio Unit", "Cantidad", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnAddProduct.setText("Agregar Producto");
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);

        btnDeleteProduct.setText("Eliminar Producto");
        btnDeleteProduct.addActionListener(this::btnDeleteProductActionPerformed);

        lblTotalAmount.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(0, 204, 0));
        lblTotalAmount.setText("Total a Pagar: $0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCashReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegisterSale)
                        .addGap(75, 75, 75)
                        .addComponent(btnBack)
                        .addGap(225, 225, 225))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddProduct)
                    .addComponent(btnDeleteProduct))
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInvoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnAddProduct)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteProduct))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotalAmount)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCashReceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategoryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegisterSale)
                                    .addComponent(btnBack))
                                .addGap(17, 17, 17))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterSaleActionPerformed
String invoiceNum = txtInvoiceNumber.getText().trim();
    int customerIndex = cmbCustomer.getSelectedIndex();
    String paymentMethod = cmbPaymentMethod.getSelectedItem() != null ? cmbPaymentMethod.getSelectedItem().toString() : "";

 
    if (invoiceNum.isEmpty() || customerIndex <= 0) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, asegúrese de tener un número de factura y un cliente seleccionado.", 
            "Datos Incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, 
            "Debe agregar al menos un producto a la tabla antes de registrar la venta.", 
            "Tabla Vacía", JOptionPane.WARNING_MESSAGE);
        return;
    }

   
    String selectedCustomerText = cmbCustomer.getSelectedItem().toString();
    String customerRuc = selectedCustomerText.split("-")[0].trim();

    
    String cashier = "Desconocido";
    if (cmbCashier.getSelectedItem() != null) {
        cashier = cmbCashier.getSelectedItem().toString();
    }

   
    javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    double totalSales = 0.0;
    for (int i = 0; i < tableModel.getRowCount(); i++) {
        totalSales += Double.parseDouble(tableModel.getValueAt(i, 4).toString());
    }
    totalSales = Math.round(totalSales * 100.0) / 100.0;

    
    double cashReceived = totalSales;
    if (paymentMethod.equalsIgnoreCase("Efectivo")) {
        String cashText = txtCashReceived.getText().trim();
        if (cashText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor ingrese el monto en efectivo recibido.", 
                "Efectivo Requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            cashReceived = Double.parseDouble(cashText);
            if (cashReceived < totalSales) {
                JOptionPane.showMessageDialog(this, 
                    "El efectivo recibido ($" + cashReceived + ") es menor al total a pagar ($" + totalSales + ").", 
                    "Efectivo Insuficiente", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, 
                "Ingrese un valor numérico válido para el efectivo recibido.", 
                "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        tableModel.setRowCount(0);
        txtCashReceived.setText("");
        lblTotalAmount.setText("Total a Pagar: $0.00");
        calculateTotal();
        lblTotalAmount.repaint();
    }

    
    try {
        MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
        MongoCollection<Document> productCollection = database.getCollection("Product");
        MongoCollection<Document> saleCollection = database.getCollection("Sales");
        MongoCollection<Document> invoiceCollection = database.getCollection("Invoices");

        java.util.Date currentDate = new java.util.Date();

        
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            String pId = tableModel.getValueAt(i, 0).toString();
            String pName = tableModel.getValueAt(i, 1).toString();
            int pQty = Integer.parseInt(tableModel.getValueAt(i, 3).toString());
            double pSubtotal = Double.parseDouble(tableModel.getValueAt(i, 4).toString());

           
            Document productDoc = productCollection.find(Filters.eq("productId", pId)).first();
            if (productDoc != null) {
                int currentStock = productDoc.getInteger("stock", 0);
                productCollection.updateOne(Filters.eq("productId", pId), Updates.set("stock", currentStock - pQty));
            }

            
            Document saleDoc = new Document("invoiceNumber", invoiceNum)
                    .append("cashier", cashier)
                    .append("customerRuc", customerRuc)
                    .append("productId", pId)
                    .append("productName", pName)
                    .append("quantity", pQty)
                    .append("total", pSubtotal)
                    .append("paymentMethod", paymentMethod)
                    .append("cashReceived", cashReceived)
                    .append("timestamp", currentDate);

            saleCollection.insertOne(saleDoc);
        }

        
        Document invoiceDoc = new Document("invoiceNumber", invoiceNum)
                .append("customerRuc", customerRuc)
                .append("cashier", cashier)
                .append("totalAmount", totalSales)
                .append("paymentMethod", paymentMethod)
                .append("cashReceived", cashReceived)
                .append("date", currentDate);

        invoiceCollection.insertOne(invoiceDoc);

        
        JOptionPane.showMessageDialog(this, 
            "Venta registrada con éxito.\nFactura Nro: " + invoiceNum + "\nTotal: $" + String.format("%.2f", totalSales), 
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        tableModel.setRowCount(0);
        txtCashReceived.setText("");
        spnQuantity.setValue(1);
        
        if (cmbCustomer.getItemCount() > 0) cmbCustomer.setSelectedIndex(0);
        if (cmbCategoryFilter.getItemCount() > 0) cmbCategoryFilter.setSelectedIndex(0);
        
        
        generateNextInvoiceNumber();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al registrar la venta en la base de datos: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegisterSaleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentMethodActionPerformed
    
    String selectedMethod = cmbPaymentMethod.getSelectedItem().toString();
    
    
    if (selectedMethod.equalsIgnoreCase("Efectivo")) {
        txtCashReceived.setEnabled(true);
        txtCashReceived.setText(""); 
    } else {
    
        txtCashReceived.setEnabled(false);
        txtCashReceived.setText("0.0");
    }
    }//GEN-LAST:event_cmbPaymentMethodActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        int productIndex = cmbProduct.getSelectedIndex();
    
   
    if (productIndex <= 0) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, seleccione un producto válido.", 
            "Producto No Seleccionado", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    int quantity = Integer.parseInt(spnQuantity.getValue().toString());
    if (quantity <= 0) {
        JOptionPane.showMessageDialog(this, 
            "La cantidad debe ser mayor a 0.", 
            "Cantidad Inválida", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        String productId = productIds.get(productIndex);
        
       
        MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
        MongoCollection<Document> collection = database.getCollection("Product");
        Document productDoc = collection.find(Filters.eq("productId", productId)).first();

        if (productDoc != null) {
            String name = productDoc.getString("name");
            double price = ((Number) productDoc.get("price")).doubleValue();
            int currentStock = productDoc.getInteger("stock", 0);

            if (quantity > currentStock) {
                JOptionPane.showMessageDialog(this, 
                    "Stock insuficiente. Solo quedan " + currentStock + " unidades disponibles.", 
                    "Stock Insuficiente", JOptionPane.WARNING_MESSAGE);
                return;
            }

           
            double subtotalRaw = price * quantity;
            double subtotal = Math.round(subtotalRaw * 100.0) / 100.0;

           
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{productId, name, price, quantity, subtotal});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al agregar producto: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    calculateTotal();
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // Usa el nombre real de tu JTable (ej: tblProducts o jTable1)
    
    
    int selectedRow = jTable1.getSelectedRow();

   
    if (selectedRow != -1) {
       
        model.removeRow(selectedRow);
        
       
        calculateTotal();
    } else {
        javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Por favor, selecciona el producto que deseas eliminar de la tabla.", 
            "Aviso", 
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
    }
   
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    
    
    
    private void loadCustomersFromMongoDB() {
        cmbCustomer.removeAllItems();
        customerIds.clear();
        
        cmbCustomer.addItem("Seleccione un cliente...");
        customerIds.add(""); 
        
        try {
            MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Customer");
            
            for (Document doc : collection.find()) {
                String ruc = doc.getString("ruc");
                String name = doc.getString("name");
                
                cmbCustomer.addItem(name + " (RUC: " + ruc + ")");
                customerIds.add(ruc); 
            }
        } catch (Exception e) {
            System.out.println("Error al cargar clientes: " + e.getMessage());
        }
    }

private void loadProductsByCategory() {
        cmbProduct.removeAllItems();
        productIds.clear();
        
        cmbProduct.addItem("Seleccione un producto...");
        productIds.add(""); 
        
        if (cmbCategoryFilter.getSelectedIndex() == 0) {
            return;
        }
        
        String selectedCategory = cmbCategoryFilter.getSelectedItem().toString();
        
        try {
            MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Product");
            
            
            for (Document doc : collection.find(Filters.eq("category", selectedCategory))) {
                String id = doc.getString("productId");
                String name = doc.getString("name");
                int stock = doc.getInteger("stock");
                
                
                cmbProduct.addItem(name + " (" + stock + " u. disponibles)");
                productIds.add(id); 
            }
        } catch (Exception e) {
            System.out.println("Error al cargar productos filrados: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FrmSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new FrmSale().setVisible(true);
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnRegisterSale;
    private javax.swing.JComboBox<String> cmbCashier;
    private javax.swing.JComboBox<String> cmbCategoryFilter;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtCashReceived;
    private javax.swing.JTextField txtInvoiceNumber;
    // End of variables declaration//GEN-END:variables

    private void loadCategoriesFromMongoDB() {
    try {
        com.mongodb.client.MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
        com.mongodb.client.MongoCollection<org.bson.Document> catCollection = database.getCollection("Categories");
        
       
        cmbCategoryFilter.removeAllItems(); 
        
 
        cmbCategoryFilter.addItem("Select a category...");
        
       
        for (org.bson.Document doc : catCollection.find()) {
            String categoryName = doc.getString("name");
            if (categoryName != null) {
                cmbCategoryFilter.addItem(categoryName);
            }
        }
    } catch (Exception ex) {
        System.out.println("Error loading categories from MongoDB: " + ex.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "Could not load categories from database.");
    }
    }
    
    private void generateNextInvoiceNumber() {
   try {
        MongoDatabase database = ec.edu.espe.Billing.utils.MongoDBConnection.getDatabase();
        MongoCollection<Document> salesCollection = database.getCollection("Sales");

        int maxInvoiceNumber = 0;

        
        for (Document doc : salesCollection.find()) {
            if (doc.containsKey("invoiceNumber")) {
                Object val = doc.get("invoiceNumber");
                int currentNum = 0;

                if (val instanceof String) {
                    try {
                        currentNum = Integer.parseInt((String) val);
                    } catch (NumberFormatException e) {
                        currentNum = 0;
                    }
                } else if (val instanceof Number) {
                    currentNum = ((Number) val).intValue();
                }

                if (currentNum > maxInvoiceNumber) {
                    maxInvoiceNumber = currentNum;
                }
            }
        }

      
        int nextNumber = maxInvoiceNumber + 1;

       
        String formattedInvoiceNumber = String.format("%08d", nextNumber);
        txtInvoiceNumber.setText(formattedInvoiceNumber);

    } catch (Exception e) {
        System.out.println("Error al generar el número de factura: " + e.getMessage());
        txtInvoiceNumber.setText("00000001");
    }
    }

    private void calculateTotal() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    double grandTotal = 0.0;
if (model.getRowCount() == 0) {
        lblTotalAmount.setText("Total a Pagar: $0.00");
        return;
    }

   
    for (int i = 0; i < model.getRowCount(); i++) {
        try {
            Object value = model.getValueAt(i, 4);
            if (value != null) {
                String cleanValue = value.toString().replace("$", "").replace(",", ".").trim();
                grandTotal += Double.parseDouble(cleanValue);
            }
        } catch (NumberFormatException e) {
          
        }
    }

  
    lblTotalAmount.setText(String.format("Total a Pagar: $%.2f", grandTotal));
    }
}
    
