/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.Billing.view;
import ec.edu.espe.Billing.Utils.MongoDBConnection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Brandon Collahuazo,CodeBros,@ESPE
 */
public class FrmLogin extends javax.swing.JFrame {
        private MongoDatabase database;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLoginNew
     */
    public FrmLogin() {
         initComponents();
        this.setLocationRelativeTo(null); 
        connectDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LA VICTORIA SUPERMARKET");

        jLabel2.setText(" Nombre de usuario:");

        jLabel3.setText(" Contraseña:");

        lblStatus.setText("Connecting to Database...");

        btnLogin.setText("Acceder");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtUsername)))
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnLogin)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addGap(27, 27, 27)
                .addComponent(btnLogin)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
         private void connectDatabase() {
        try {
            database = MongoDBConnection.getDatabase();
            if (database != null) {
                lblStatus.setText("Successfully connected to MongoDB Atlas.");
                lblStatus.setForeground(new Color(0, 153, 51));
            } else {
                lblStatus.setText("Connection error: database returned null.");
                lblStatus.setForeground(Color.RED);
            }
        } catch (Exception e) {
            lblStatus.setText("Error connecting to Database.");
            lblStatus.setForeground(Color.RED);
            JOptionPane.showMessageDialog(this, 
                "Could not establish connection with database:\n" + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please fill in all required fields.", 
                "Missing Data", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (username.equals("MayraJHF") && password.equals("171206")) {
            JOptionPane.showMessageDialog(this, 
                "Access granted! Welcome to La Victoria Supermarket.", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
            java.awt.EventQueue.invokeLater(() -> {
                FrmMenu mainMenu = new FrmMenu("admin");
                mainMenu.setVisible(true);
            });
            return;
        } 
        
        if (username.equals("santiagolomas") && password.equals("santiago123")) {
            JOptionPane.showMessageDialog(this, 
                "Access granted!\nWelcome, Cashier Santiago Lomas.", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            java.awt.EventQueue.invokeLater(() -> {
                FrmMenu mainMenu = new FrmMenu("cashier");
                mainMenu.setVisible(true);
            });
            return;
        } 
        
        if (username.equals("mateolomas") && password.equals("mateo123")) {
            JOptionPane.showMessageDialog(this, 
                "Access granted!\nWelcome, Cashier Mateo Lomas.", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            java.awt.EventQueue.invokeLater(() -> {
                FrmMenu mainMenu = new FrmMenu("cashier");
                mainMenu.setVisible(true);
            });
            return;
        } 
        
        try {
            com.mongodb.client.MongoDatabase db = MongoDBConnection.getDatabase();
            com.mongodb.client.MongoCollection<org.bson.Document> usersCollection = db.getCollection("Users");
            org.bson.Document userQuery = usersCollection.find(com.mongodb.client.model.Filters.eq("username", username)).first();
            
            if (userQuery != null) {
                String passwordBD = userQuery.getString("password");
                String role = userQuery.getString("role");
                
                if (password.equals(passwordBD)) {
                    JOptionPane.showMessageDialog(this, 
                        "Access granted! Role: " + role.toUpperCase(), 
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    java.awt.EventQueue.invokeLater(() -> {
                        FrmMenu mainMenu = new FrmMenu(role);
                        mainMenu.setVisible(true);
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect password.", "Authentication Failure", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "User does not exist in database.", "Authentication Failure", JOptionPane.ERROR_MESSAGE);
                txtPassword.setText("");
                txtUsername.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Connection error while validating user: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
