/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.Billing.view;
import javax.swing.JOptionPane;
/**
 *
 * @author Brandon Collahuazo,CodeBros,@ESPE
 */
public class FrmMenu extends javax.swing.JFrame {
    private String userRole;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenuNew
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public FrmMenu(String role) {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.userRole = role;
        applyRoleRestrictions();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCompany = new javax.swing.JMenu();
        itmRegisterCompany = new javax.swing.JMenuItem();
        mnuCustomer = new javax.swing.JMenu();
        itmRegisterCustomer = new javax.swing.JMenuItem();
        itmDeleteCustomer = new javax.swing.JMenuItem();
        mnuProduct = new javax.swing.JMenu();
        itmRegisterProduct = new javax.swing.JMenuItem();
        itmDeleteProduct = new javax.swing.JMenuItem();
        itmViewInventory = new javax.swing.JMenuItem();
        mnuSales = new javax.swing.JMenu();
        itmCreateSale = new javax.swing.JMenuItem();
        itmPrintInvoice = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO LA VICTORIA SUPERMARKET SYSTEM");

        mnuCompany.setText("Compañía");

        itmRegisterCompany.setText(" Registrar empresa");
        itmRegisterCompany.addActionListener(this::itmRegisterCompanyActionPerformed);
        mnuCompany.add(itmRegisterCompany);

        jMenuBar1.add(mnuCompany);

        mnuCustomer.setText(" Cliente");

        itmRegisterCustomer.setText(" Registrar cliente");
        itmRegisterCustomer.addActionListener(this::itmRegisterCustomerActionPerformed);
        mnuCustomer.add(itmRegisterCustomer);

        itmDeleteCustomer.setText(" Eliminar cliente");
        itmDeleteCustomer.addActionListener(this::itmDeleteCustomerActionPerformed);
        mnuCustomer.add(itmDeleteCustomer);

        jMenuBar1.add(mnuCustomer);

        mnuProduct.setText(" Producto");

        itmRegisterProduct.setText(" Registrar producto");
        itmRegisterProduct.addActionListener(this::itmRegisterProductActionPerformed);
        mnuProduct.add(itmRegisterProduct);

        itmDeleteProduct.setText(" Eliminar producto");
        itmDeleteProduct.addActionListener(this::itmDeleteProductActionPerformed);
        mnuProduct.add(itmDeleteProduct);

        itmViewInventory.setText(" Ver inventario");
        itmViewInventory.addActionListener(this::itmViewInventoryActionPerformed);
        mnuProduct.add(itmViewInventory);

        jMenuBar1.add(mnuProduct);

        mnuSales.setText(" Ventas");

        itmCreateSale.setText(" Realizar venta");
        itmCreateSale.addActionListener(this::itmCreateSaleActionPerformed);
        mnuSales.add(itmCreateSale);

        itmPrintInvoice.setText(" Imprimir factura");
        itmPrintInvoice.addActionListener(this::itmPrintInvoiceActionPerformed);
        mnuSales.add(itmPrintInvoice);

        jMenuBar1.add(mnuSales);

        mnuReports.setText("Reportes ");
        mnuReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuReportsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuReports);

        menuExit.setText("Salir");
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void applyRoleRestrictions() {
        if ("cashier".equalsIgnoreCase(userRole)) {
            mnuReports.setEnabled(false); 
        }
    }
    private void itmRegisterCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegisterCompanyActionPerformed
        FrmCompany companyFrame = new FrmCompany();
        companyFrame.setVisible(true);
    }//GEN-LAST:event_itmRegisterCompanyActionPerformed

    private void itmRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegisterCustomerActionPerformed
        ec.edu.espe.Billing.view.FrmCustomerRegistration customerRegFrame = new ec.edu.espe.Billing.view.FrmCustomerRegistration();
        customerRegFrame.setVisible(true);
    }//GEN-LAST:event_itmRegisterCustomerActionPerformed

    private void itmDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDeleteCustomerActionPerformed
        ec.edu.espe.Billing.view.FrmDeleteCustomer deleteCustFrame = new ec.edu.espe.Billing.view.FrmDeleteCustomer();
        deleteCustFrame.setVisible(true);
    }//GEN-LAST:event_itmDeleteCustomerActionPerformed

    private void itmRegisterProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegisterProductActionPerformed
        ec.edu.espe.Billing.view.FrmProductRegistration productRegFrame = new ec.edu.espe.Billing.view.FrmProductRegistration();
        productRegFrame.setVisible(true);
    }//GEN-LAST:event_itmRegisterProductActionPerformed

    private void itmDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmDeleteProductActionPerformed
        FrmDeleteProduct deleteProdFrame = new FrmDeleteProduct();
        deleteProdFrame.setVisible(true);
    }//GEN-LAST:event_itmDeleteProductActionPerformed

    private void itmViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewInventoryActionPerformed
        FrmShowStock stockFrame = new FrmShowStock();
        stockFrame.setVisible(true);
    }//GEN-LAST:event_itmViewInventoryActionPerformed

    private void itmCreateSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCreateSaleActionPerformed
        ec.edu.espe.Billing.view.FrmSale saleFrame = new ec.edu.espe.Billing.view.FrmSale();
        saleFrame.setVisible(true);
    }//GEN-LAST:event_itmCreateSaleActionPerformed

    private void itmPrintInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPrintInvoiceActionPerformed
        ec.edu.espe.Billing.view.FrmPrintInvoice printFrame = new ec.edu.espe.Billing.view.FrmPrintInvoice();
        printFrame.setVisible(true);
    }//GEN-LAST:event_itmPrintInvoiceActionPerformed

    private void mnuReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuReportsMouseClicked
        ec.edu.espe.Billing.view.FrmReport reportFrame = new ec.edu.espe.Billing.view.FrmReport();
        reportFrame.setVisible(true);
    }//GEN-LAST:event_mnuReportsMouseClicked

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        int response = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to exit the system?", 
            "Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
    }//GEN-LAST:event_menuExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCreateSale;
    private javax.swing.JMenuItem itmDeleteCustomer;
    private javax.swing.JMenuItem itmDeleteProduct;
    private javax.swing.JMenuItem itmPrintInvoice;
    private javax.swing.JMenuItem itmRegisterCompany;
    private javax.swing.JMenuItem itmRegisterCustomer;
    private javax.swing.JMenuItem itmRegisterProduct;
    private javax.swing.JMenuItem itmViewInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu mnuCompany;
    private javax.swing.JMenu mnuCustomer;
    private javax.swing.JMenu mnuProduct;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuSales;
    // End of variables declaration//GEN-END:variables
}
